=== MateoGlezG/UNI-PIAT/Apuntes/esquema_infSonda.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://upm.es/crowdsense"
           xmlns:tns="http://upm.es/crowdsense"
           elementFormDefault="qualified">

    <xs:simpleType name="MacType"> <xs:restriction base="xs:string">
            <xs:pattern value="([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="RssiType"> <xs:restriction base="xs:int">
            <xs:minInclusive value="-100"/>
            <xs:maxInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:group name="GeoGroup">
        <xs:sequence>
            <xs:element name="Lat" type="xs:float"/>
            <xs:element name="Lon" type="xs:float"/>
        </xs:sequence>
    </xs:group>

    <xs:attributeGroup name="CabeceraSonda">
        <xs:attribute name="idSonda" type="xs:string" use="required"/>
        <xs:attribute name="timestamp" type="xs:dateTime" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="EventoBaseType"> <xs:attribute name="nivelBateria" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="EventoWifiType"> <xs:complexContent>
            <xs:extension base="tns:EventoBaseType">
                <xs:sequence>
                    <xs:element name="Ssid" type="xs:string"/>
                    <xs:element name="Mac" type="tns:MacType"/>
                    <xs:element name="Rssi" type="tns:RssiType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="InformeSonda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ubicacion">
                    <xs:complexType> <xs:group ref="tns:GeoGroup"/> </xs:complexType>
                </xs:element>
                <xs:element name="ListaEventos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="EventoWifi" type="tns:EventoWifiType"
                                        maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attributeGroup ref="tns:CabeceraSonda"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== MateoGlezG/UNI-PIAT/Apuntes/informeSonda.xml
<?xml version="1.0" encoding="UTF-8"?>
<cs:InformeSonda
    xmlns:cs="http://upm.es/crowdsense"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://upm.es/crowdsense esquema_infSonda.xsd"
    idSonda="SP-2024-05"
    timestamp="2024-01-20T14:30:00">

    <cs:Ubicacion>
        <cs:Lat>40.45</cs:Lat>
        <cs:Lon>-3.72</cs:Lon>
    </cs:Ubicacion>

    <cs:ListaEventos>
        <cs:EventoWifi nivelBateria="85">
            <cs:Ssid>Eduroam</cs:Ssid>
            <cs:Mac>AA:BB:CC:11:22:33</cs:Mac> 
            <cs:Rssi>-65</cs:Rssi>             
        </cs:EventoWifi>
        
        <cs:EventoWifi nivelBateria="84">
            <cs:Ssid>UPM-Guest</cs:Ssid>
            <cs:Mac>11:22:33:AA:BB:CC</cs:Mac>
            <cs:Rssi>-40</cs:Rssi>
        </cs:EventoWifi>
    </cs:ListaEventos>

</cs:InformeSonda>
